version: '3.9'

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - 3001:3001
    volumes:
      - ./api/:/api
    environment:
      - NODE_ENV=development
      - PORT=3001
    command: npm run start

  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - 5173:5173
    volumes:
      - ./app:/usr/src/app
    environment:
      - NODE_ENV=development


  mongo:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db